[package]
name = "ai-trading-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
alpha_vantage = "0.11.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
tokio = { version = "1.43.0", features = ["full"] }